source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

pod 'Parse'
pod 'ParseUI'

target 'ParseLoginDemo' do
end

target 'ParseLoginDemoTests' do
end

target 'ParseLoginDemoUITests' do
end
