source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!


def bluemix_pods
  # https://github.com/ibm-bluemix-mobile-services/bms-clientsdk-swift-core
  pod 'BMSCore'
  # https://github.com/ibm-bluemix-mobile-services/bms-clientsdk-swift-security
  pod 'BMSSecurity'
end

target 'StrongLoopClientDemo' do
  # https://github.com/ishkawa/APIKit
  pod 'APIKit', '~> 1.3.0'

  # bluemix_pods

  # https://github.com/SwiftyJSON/SwiftyJSON
  # pod 'SwiftyJSON'

  # https://github.com/hkellaway/Gloss
  # pod 'Gloss'

  # https://github.com/icanzilb/SwiftSpinner
  pod 'SwiftSpinner'

  # https://github.com/Alamofire/Alamofire
  pod 'Alamofire'

  # https://github.com/malcommac/SwiftDate
  # pod 'SwiftDate'


  # 使用するかもしれないライブラリ

# https://github.com/duemunk/Async
#  pod 'AsyncSwift'

# https://github.com/andresinaka/SwiftCop
#  pod 'SwiftCop'

# https://github.com/ikesyo/Himotoki
# pod "Himotoki", "~> 2.0"
end
