# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'RACPlayground' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

#  pod 'RxSwift'
#  pod 'RxCocoa'
  pod 'Bond', '~> 4.0'
  pod 'ReactiveCocoa'
  pod 'youtube-ios-player-helper'
  pod 'Loggerithm'
  
  target 'RACPlaygroundTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
