source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

target 'YoutubeClient' do
  pod "youtube-parser"
end

target 'YoutubeClientTests' do
  pod "youtube-parser"
end

target 'YoutubeClientUITests' do

end
