source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

# link_with 'NCMB_iOSAppDemo', 'NCMB_iOSAppDemoTests'

target "NCMB_iOSAppDemo" do
  pod 'NCMB', :git => 'https://github.com/NIFTYCloud-mbaas/ncmb_ios.git'
end

# Facebook
 # pod 'FBSDKCoreKit'
 # pod 'FBSDKLoginKit'
 # pod 'FBSDKShareKit'
 # pod 'FBSDKMessengerShareKit'

# target :NCMB_iOSAppDemoTests, :exclusive => true do
#   # pod 'FBSnapshotTestCase'
# end

# pod 'SwiftyJSON'
# pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git', :branch => 'xcode7'
 # pod 'XCGLogger'

# UI
# pod 'SVProgressHUD', '~> 1.1'

# pod 'SDWebImage'
